# Generated by Django 4.1.7 on 2023-04-03 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_creation_time_remove_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creation_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
